version: '3'

services:
  mysql:
    image: mysql:8.0.13
    container_name: mysql
    hostname: ${DB_HOST}
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/backup:/var/lib/mysql
    networks:
      - server-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-wordpress
    hostname: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}:${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${PHPMYADMIN_UP_LIMIT}

    depends_on:
      - mysql
    networks:
      - server-network

networks:
  server-network:
    external: true
